#!/bin/sh

set -x
set -v

CXXFLAGS="-g -pipe -Wextra -Wno-missing-field-initializers -Wmissing-include-dirs -Wfloat-equal -Wpointer-arith -Wwrite-strings -Wshadow -O3 \
		-march=corei7-avx -std=c++11 -lpthread -ltcmalloc"

g++ ${CXXFLAGS} *.cc SP/*.cpp -o filter -ISP

